apiVersion: v1
kind: ConfigMap
metadata:
  name: recruitment-app-config
data:
  PORT: "3000"
  DB_NAME: "hr_system"
  MONGO_URI: "mongodb://rootuser:rootpassword@mongo:27017/hr_system?authSource=admin"
  MONGO_USERNAME: "rootuser"
  MONGO_PASSWORD: "rootpassword"
